# Jekyll 配置
theme: jekyll-theme-cayman  # 单栏全宽主题，无侧边栏
title: Awesome Solana Libraries
description: 全面的 Solana 生态系统知识库
lang: zh-CN
encoding: UTF-8
show_downloads: false  # 不显示下载按钮

# 中文支持
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# 插件
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Sass 配置
sass:
  style: compressed

# 博客配置
blog:
  enabled: true

# 作者信息
author:
  name: "Awesome Solana Team"
  email: "noreply@awesome-solana.com"
  bio: "专注于 Solana 生态系统的技术分享和知识传播"
  avatar: "/assets/images/avatar.png"

# 时区和日期格式
timezone: Asia/Shanghai
date_format: "%Y年%m月%d日"

# 分页配置 (基础版本，GitHub Pages 原生支持)
paginate: 5
paginate_path: "/blog/page:num/"

# 博客相关路径
blog_path: "/blog"
categories_path: "/categories"
tags_path: "/tags"

# Feed 配置
feed:
  posts_limit: 20
  excerpt_only: false

# 相对链接支持
relative_links:
  enabled: true
  collections: true

# 包含文件
include:
  - README.md
  - transaction-services
  - arbitrage
  - dependencies
  - dex-market-makers
  - mcp
  - resources
  - rpc

# 排除文件
exclude:
  - .git
  - .claude
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - setup-pages.sh